# 
# +--------------------------------------+
# |                 INFO                 |
# +--------------------------------------+
# If you want to use special characters in this document, such as accented letters, you MUST save the file as UTF-8, not ANSI
# If any Errors show up when vBox loads please double check these points
#    - No tabs are used in the YAML file. YAML only allows spaces
#    - Indents are correct
#    - Check all Apostrophes if they are correctly placed.
#    - that text with symbols in it are enclosed in single or double quotes.

# +--------------------------------------+
# |                 SPAWN                |
# +--------------------------------------+
# Please do NOT touch this, This is to locate your set spawn!
spawn.world:
spawn.x:
spawn.y:
spawn.z:

# +--------------------------------------+
# |                 CHAT                 |
# +--------------------------------------+

# default enableNoCaps = true
enableNoCaps: true

# Enable/disable overriding of messages when caps detected
enableMessageOverride: false

# Message to override player message if enabled
overrideMessage: "I like purple penguins!"

# Enable/disable sending a message to a player when caps detected
enablePlayerMessage: true

# Message to send to player if enabled
playerMessage: "Sorry, but you used too many caps!"

# Enable/disable forcing lowercase on all messages
# MessageOverride must be disabled to use this feature
enableForceLowercase: false

# Maximum caps to allow in a row
# Allows everything lower than this number
capsInRow: 5

# Maximum percentage of caps in the message to allow
totalCapsPercentage: 50

# Phrases to ignore when forcing lowercase
whitelist:
  - "I"
  - "TS"
  - "IP"
  - "US"
  - ":D"
  - ":P"
  - "LOL"
  
# Cursewords Censored words
censoredwords:
- fuck
- shit
- bitch
- ass
- arse
- arsehole
- cunt
# +--------------------------------------+
# |                MySQL                 |
# +--------------------------------------+

# If you want to use MySQL for this plugin
use-mysql: true
# Please set your MySQL Credentials Here!
mysql-user: minecraft
mysql-password: root
mysql-database: vbox

# +--------------------------------------+
# |             BAN SYSTEM               |
# +--------------------------------------+

broadcast.warn: "&6You were warned by &e%admin%&6 Reason &e%reason%"
broadcast.Kick: "&6Player &e%victim%&6 was kicked by &e%admin%&6! Reason: &e%reason%"
broadcast.TempBan: "&6Player &e%victim%&6 was temp-banned by &e%admin%&6 for &e%time% &6Reason: &e%reason%"
broadcast.Ban: "&6Player &e%victim%&6 was banned by &e%admin%&6! Reason: &e%reason%"
broadcast.Unban: "&e%victim%&6 was unbanned by &e%admin%&6!"
